In [1]:
import numpy as np

In [3]:
arr1 = np.array([[10,20],[30,40]], dtype=np.float)

C:\Users\2ABB~1\AppData\Local\Temp/ipykernel_8464/395403625.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr1 = np.array([[10,20],[30,40]], dtype=np.float)


In [4]:
arr1

array([[10., 20.],
       [30., 40.]])

In [5]:
arr1.shape

(2, 2)

In [6]:
arr1.ndim

2

In [7]:
arr2 = np.arange(5, 11, 2.5)
arr2

array([ 5. ,  7.5, 10. ])

In [8]:
arr1 = np.arange(1, 20)

In [9]:
arr1.ndim

1

In [10]:
arr1.shape

(19,)

In [11]:
np.sqrt(np.std(arr1))

2.340347319320716

In [12]:
mtr1 = np.array([[1, 2, 3], [4, 5, 6]])
mtr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
mtr2= np.array([[7, 8, 9], [10, 11, 12]])
mtr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [17]:
mtr_sum = mtr1 + mtr2
mtr_sum

array([[ 8, 10, 12],
       [14, 16, 18]])

In [19]:
mtr_concat = np.concatenate((mtr1, mtr2))

In [20]:
mtr_concat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
mtr_bigger_than_4 = mtr_concat[(mtr_concat>4)]

In [22]:
mtr_bigger_than_4

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
mtr_slicing = mtr_concat[0]
mtr_slicing

array([1, 2, 3])

In [24]:
mtr_concat[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
mtr_slicing[0:0:3]

array([], dtype=int32)