In [1]:
import numpy as np

In [8]:
arr1 = np.array([1, 2, 3, 4, 5])

In [9]:
arr1.shape

(5,)

In [10]:
arr1.dtype

dtype('int32')

In [11]:
arr1.ndim

1

In [13]:
arr2 = np.arange(0, 10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr3 = np.arange(0, 10, 1.5)
arr3

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [16]:
arr2_sqrt = np.sqrt(arr2)
arr2_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [17]:
arr1 = np.arange(10 , 20)

In [19]:
arr1 + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr1.max()

9

In [22]:
arr1.mean()

4.5

In [23]:
arr1.sum()

45

In [24]:
arr1.std()

2.8722813232690143

In [25]:
arr1 > 8

array([False, False, False, False, False, False, False, False, False,
        True])

In [28]:
arr5 = np.arange(50, 55)
arr5

array([50, 51, 52, 53, 54])

In [30]:
arr5.ndim

1

In [31]:
arr5.shape

(5,)

In [34]:
a = arr5.std()
a

1.4142135623730951

In [40]:
b = np.sqrt(a)
b

1.189207115002721

In [44]:
arr = np.concatenate((arr1, arr2))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[(arr < 5)]

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [48]:
arr[(arr < 3) & (arr > 7)]
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
matrix = np.array([(1, 2, 3), (4, 5 , 6), (7, 8, 9), (10, 11, 12)])
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
matrix.shape

(2, 3)

In [52]:
matrix.ndim

2

In [53]:
matrix.size

6

In [59]:
matrix2 = np.array([(3, 4), (5, 6), (7, 8), (9, 10), (11, 12)])
matrix2

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [61]:
np.mean(matrix2, axis=0)

array([7., 8.])